#74 Feature/team view
BinaryStudioAcademy/bsa-2022-easymeets pull request #100
Opened 2022-08-19 15:39 UTC by EvgenValko

![Screenshot_41](https://user-images.githubusercontent.com/79512847/185655805-85adbd8c-cc32-415c-a147-bb7f76d43045.png)

2022-08-19 16:40 UTC, tatianahutii requested changes

2022-08-19 16:40 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/TeamService.cs
> +        return Task.FromResult(!teams.Any());
It would be better to combine where and Any to 
AnyAsync(...predicate...)

2022-08-19 16:40 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/TeamService.cs
> +        }
It would be better to combine where and Any to
AnyAsync(...predicate...)

2022-08-19 16:40 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/TeamService.cs
> +        return await Task.FromResult($"{pageLink}{index}");
See the previous comments

2022-08-19 16:40 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/TeamService.cs
> +        var user = await _userService.GetCurrentUserAsync();
You can load user after SaneChanges()
it will more logically

2022-08-19 16:40 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/TeamController.cs
> +        }
I believe as we have check to null in the service we don't need this check here

2022-08-19 16:40 UTC, tatianahutii commented on frontend/src/app/core/services/team.service.ts
> +    }
Why you cannot send just object?

2022-08-19 16:40 UTC, tatianahutii commented on frontend/src/app/modules/settings/team/team-preferences/team-preferences.component.ts
> +                    this.isNewTeam = true;
We can just redirect to the account setting (personal setting page)

2022-08-19 16:40 UTC, tatianahutii commented on frontend/src/app/modules/settings/team/team-preferences/team-preferences.component.ts
> +        }
```suggestion
        this.isNewTeam
            ? this.createTeam(form);
            : this.editeTeam(form);
```

2022-08-19 16:40 UTC, tatianahutii commented on frontend/src/app/modules/settings/team/team-preferences/team-preferences.component.ts
> +        }
Please refactor these lines, and make logic simpler

2022-08-19 16:40 UTC, tatianahutii commented on frontend/src/app/modules/settings/team/team-preferences/team-preferences.component.ts
> +        };
private methods after public

2022-08-19 16:40 UTC, tatianahutii commented on frontend/src/app/modules/settings/team/team-preferences/team-preferences.component.ts
> +                    .pipe(this.untilThis)
You need to unsubscribe from every request

2022-08-19 18:29 UTC, EvgenValko commented on frontend/src/app/modules/settings/team/team-preferences/team-preferences.component.ts
> +        }
I tried that and got an eslint error

2022-08-22 10:48 UTC, tatianahutii approved these changes
LGTM

2022-08-22 10:48 UTC, merged