Card 105 Landing routing updated to not allow authorized users
BinaryStudioAcademy/bsa-2022-easymeets pull request #106
Opened 2022-08-19 18:35 UTC by YuraRiabov

2022-08-19 19:32 UTC, tatianahutii requested changes

2022-08-19 19:32 UTC, tatianahutii commented on frontend/src/app/core/guards/landing.guard.ts
> +    canActivate(): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {
You can don't write output type

2022-08-19 20:07 UTC, YuraRiabov commented on frontend/src/app/core/guards/landing.guard.ts
> +    canActivate(): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {
Done

2022-08-21 08:53 UTC, tatianahutii approved these changes
LGTM

2022-08-21 08:56 UTC, merged