Card #129 Fix bug with repeating phone number code
BinaryStudioAcademy/bsa-2022-easymeets pull request #135
Opened 2022-08-22 22:12 UTC by Erbidium

2022-08-23 08:57 UTC, apofis96 requested changes
Inefficient and possibly buggy solution. Change it to store code and number separately

2022-08-24 14:14 UTC, Erbidium commented
> Inefficient and possibly buggy solution. Change it to store code and number separately

Reworked solution of the problem

2022-08-25 08:27 UTC, tatianahutii approved these changes
LGTM

2022-08-25 09:58 UTC, apofis96 approved these changes

2022-08-25 10:05 UTC, merged