[#101] Separate page of bookers if there are >3 implemented
BinaryStudioAcademy/bsa-2022-easymeets pull request #137
Opened 2022-08-23 12:29 UTC by YuraRiabov

![Screenshot_584](https://user-images.githubusercontent.com/88149444/186158253-7245d27e-5144-40ac-9137-1a43d6fe343f.png)

2022-08-23 17:40 UTC, tatianahutii requested changes

2022-08-23 17:40 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/MappingProfiles/MeetingProfile.cs
> +            return GetAllParticipants(meeting).Take(3).ToList();
It is not a good idea to load all and only after that take 3 items

2022-08-23 17:40 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/MeetingService.cs
> +            }
```suggestion
                .FirstOrDefaultAsync(m => m.Id == id) ??  throw new KeyNotFoundException("No meeting found");
```

2022-08-23 17:40 UTC, tatianahutii commented on frontend/src/app/modules/bookings/bookers-page/bookers-page.component.ts
> +                });
please handle errors

2022-08-24 14:09 UTC, tatianahutii approved these changes

2022-08-25 07:14 UTC, apofis96 approved these changes

2022-08-25 07:17 UTC, merged