#80 Feature/upload team logo
BinaryStudioAcademy/bsa-2022-easymeets pull request #138
Opened 2022-08-23 15:07 UTC by EvgenValko

2022-08-23 15:25 UTC, tatianahutii requested changes

2022-08-23 15:25 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/TeamController.cs
> +        }
we have global error handler
and all checks should be in a service

2022-08-23 15:25 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/UserController.cs
> +                }
```suggestion
                var imageUrl = await _userService.UploadImageAsync(file); if (imageUrl is null) ?? NotFound();
```

2022-08-23 15:25 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/UserController.cs
> +                }
and please change exeption type

2022-08-23 15:25 UTC, tatianahutii commented on frontend/src/app/modules/settings/team/team-preferences/team-preferences.component.ts
> +            );
please move this to a separate method

2022-08-23 19:07 UTC, tatianahutii approved these changes

2022-08-25 07:15 UTC, tatianahutii requested changes

2022-08-25 07:15 UTC, tatianahutii commented on frontend/src/app/modules/settings/team/team-preferences/team-preferences.component.html
> +                <div class="logo" style="background-image: url('{{ imageUrl }}')"></div>
Please to not use inline styles

2022-08-25 07:20 UTC, apofis96 requested changes

2022-08-25 07:20 UTC, apofis96 commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/UserService.cs
> +            if (currentUser == null)
use "is" operator

2022-08-25 07:20 UTC, apofis96 commented on backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/TeamController.cs
> +        return Ok(new { imagePath = imageUrl });
Define dto, cause in swagger it will be unclear what this method returns

2022-08-25 07:20 UTC, apofis96 commented on backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/UserController.cs
> +        public async Task<IActionResult> UploadImageAsync([FromForm] IFormFile file)
dto x2

2022-08-26 09:07 UTC, tatianahutii approved these changes

2022-08-26 09:27 UTC, apofis96 approved these changes

2022-08-26 09:27 UTC, merged