Feature/notification emails page #113
BinaryStudioAcademy/bsa-2022-easymeets pull request #139
Opened 2022-08-23 18:30 UTC by koval0v

![image](https://user-images.githubusercontent.com/71783287/186236335-a25fedb0-9c9f-447a-9b8a-eb4d43b54f09.png)
![image](https://user-images.githubusercontent.com/71783287/186236370-c2a8f277-1f84-4eaa-a26f-36ef7f1b3412.png)

2022-08-24 14:40 UTC, tatianahutii requested changes

2022-08-24 14:40 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/notification-emails/notification-emails.component.sass
> +    grid-area: item4
It would be better to give more  sense to these names

2022-08-24 14:40 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/notification-emails/notification-emails.component.sass
> +    height: 200px
please do not use px

2022-08-24 14:47 UTC, koval0v commented
![image](https://user-images.githubusercontent.com/71783287/186449169-201e9818-0cd9-4e97-9f63-b04e5c7db364.png)

2022-08-25 09:55 UTC, tatianahutii requested changes

2022-08-25 09:55 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/notification-emails/notification-emails.component.sass
> +#container-toggle
change grid areas as well

2022-08-25 09:55 UTC, tatianahutii requested changes

2022-08-25 09:55 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/notification-emails/notification-emails.component.sass
> +    height: 22vh
Why now %?

2022-08-25 10:25 UTC, tatianahutii approved these changes

2022-08-25 10:29 UTC, apofis96 approved these changes

2022-08-25 11:12 UTC, merged