#137 Bug/incorrect photo size
BinaryStudioAcademy/bsa-2022-easymeets pull request #144
Opened 2022-08-24 07:28 UTC by EvgenValko

2022-08-24 14:35 UTC, tatianahutii approved these changes
LGTM

2022-08-25 07:26 UTC, apofis96 submitted a review, later dismissed

2022-08-25 07:26 UTC, tatianahutii requested changes

2022-08-25 07:26 UTC, tatianahutii commented on frontend/src/app/modules/settings/user/user-profile-page/user-profile-page.component.html
> +                <div class="user-avatar" style="background-image: url('{{ imageUrl }}')"></div>
Please do not use inline styles

2022-08-25 11:01 UTC, tatianahutii approved these changes

2022-08-26 09:11 UTC, apofis96 approved these changes

2022-08-26 09:12 UTC, merged