Adding id to custom claims on sign up and sign in
BinaryStudioAcademy/bsa-2022-easymeets pull request #148
Opened 2022-08-25 11:49 UTC by Ymkavi

Environment variable "Firebase_Service_Account_Private_Key" with private key must be added

2022-08-26 12:57 UTC, apofis96 requested changes
Fix conflicts please.
And git warnings

2022-08-26 13:41 UTC, apofis96 commented
Add an method to obtain identity from context.

2022-08-26 14:04 UTC, apofis96 approved these changes

2022-08-26 14:22 UTC, tatianahutii requested changes

2022-08-26 14:22 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/UserService.cs
> +            return email!.Value;
Why not Id?
And I believe we already have this method

2022-08-26 14:22 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.WebAPI/service-account-file.json
> +}
Please move private items to environment variables

2022-08-26 14:23 UTC, tatianahutii requested changes

2022-08-26 14:23 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.WebAPI/service-account-file.json
> +}
And delete this file
Not security to appsetting file
Secure to environment variables

2022-08-26 14:40 UTC, apofis96 requested changes

2022-08-26 14:40 UTC, apofis96 commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/UserService.cs
> +            var userRecord = await _firebaseAuth.GetUserAsync(uid);
Why you don't use claims from context?
Move this method to appropriate place.

2022-08-31 15:29 UTC, apofis96 approved these changes

2022-09-01 08:02 UTC, tatianahutii approved these changes

2022-09-02 11:18 UTC, merged