#144 Added confirmation windows when deleting a slot or team
BinaryStudioAcademy/bsa-2022-easymeets pull request #150
Opened 2022-08-25 13:19 UTC by Ymkavi

![image](https://user-images.githubusercontent.com/58224993/186675642-a91ef500-6561-4e7f-ac81-ed10132a24d4.png)

2022-08-25 15:51 UTC, tatianahutii requested changes

2022-08-25 15:51 UTC, tatianahutii commented on frontend/src/app/modules/availability/edit-slot/edit-availability-page/edit-availability-page.component.ts
> +            this.http.getSlotById(this.id).subscribe((slotResponse) => {
you need to unsubscribe

2022-08-26 09:29 UTC, tatianahutii approved these changes

2022-08-26 10:01 UTC, apofis96 approved these changes

2022-08-26 10:10 UTC, merged