#110 Feature/weekly schedule view
BinaryStudioAcademy/bsa-2022-easymeets pull request #170
Opened 2022-08-28 11:28 UTC by EvgenValko

2022-08-28 13:24 UTC, tatianahutii requested changes

2022-08-28 13:24 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.Common/Enums/WeekDay.cs
> +    Saturday
I believe this can break out existed logic

2022-08-28 13:24 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/new-availability/new-availability.component.html
> +            <div [className]="getClass(3)"><app-notification-emails [newSlot]="slot"></app-notification-emails></div>
please red rid of magic numbers

2022-08-28 13:24 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/new-availability/new-availability.component.ts
> +    public enableSlot() {
You can omi "public" for public methods

2022-08-28 13:24 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/new-availability/new-availability.component.ts
> +    }
why do we need this?

2022-08-28 13:24 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/schedule-week/schedule-week.component.html
> +    >
```suggestion
        (eventTimesChanged)="eventTimesChanged($event)">
```

2022-08-28 13:24 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/schedule-week/schedule-week.component.ts
> +        event.end = newEnd as Date;
please get rid of mutation

2022-08-28 13:24 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/schedule-week/schedule-week.component.ts
> +        if (newEnd !== undefined) {
```suggestion
        if (newEnd) {
```

2022-08-28 13:24 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/schedule-week/schedule-week.component.ts
> +        if (newEnd !== undefined) {
```suggestion
        if (newEnd) {
```

2022-08-28 13:24 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/schedule-week/schedule-week.component.ts
> +        this.items[index].start = `${this.reformat(newStart.getHours())}:${this.reformat(newStart.getMinutes())}:00`;
we need somehow get rid of index

2022-08-28 13:24 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/schedule-week/schedule-week.component.ts
> +                    ), this.parseTime(item.end).getMinutes()),
create generic method for this and use it for start and end

2022-08-28 13:24 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/schedule-week/schedule-week.component.ts
> +        this.items.forEach((item) => {
why did you use foreach?

2022-08-28 19:07 UTC, tatianahutii requested changes

2022-08-28 19:07 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/schedule-week/schedule-week.component.ts
> +    private recalculateDayIndexForCalenfar(weekDayIndex: number): number {
Please fix typo and git warning

2022-08-29 11:07 UTC, koval0v approved these changes

2022-08-29 11:11 UTC, tatianahutii approved these changes

2022-08-29 11:12 UTC, merged