Bug/team name left menu
BinaryStudioAcademy/bsa-2022-easymeets pull request #184
Opened 2022-08-29 16:21 UTC by koval0v

![image](https://user-images.githubusercontent.com/71783287/187247930-d1791415-86dc-4461-936d-aab01348e3e4.png)

2022-08-29 18:38 UTC, apofis96 requested changes
Add "..." to the end if overflows

2022-08-29 18:44 UTC, PublicFedorenko approved these changes

2022-08-30 12:23 UTC, koval0v commented
![image](https://user-images.githubusercontent.com/71783287/187435535-95ffd4e1-b0ac-4644-a0bd-e21e6928e5d5.png)
![image](https://user-images.githubusercontent.com/71783287/187435573-c75e13f7-cd35-4c32-b976-691fa9f73ce4.png)

2022-08-30 12:25 UTC, apofis96 approved these changes

2022-08-30 13:44 UTC, tatianahutii approved these changes

2022-08-30 13:44 UTC, merged