Fixes #178 Allow user registration form signIn view
BinaryStudioAcademy/bsa-2022-easymeets pull request #191
Opened 2022-08-29 19:02 UTC by PublicFedorenko

2022-08-29 19:09 UTC, tatianahutii approved these changes

2022-08-29 19:14 UTC, apofis96 approved these changes

2022-08-30 08:44 UTC, Erbidium requested changes

2022-08-30 08:44 UTC, Erbidium commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/UserService.cs
> +            var userEntity = await _context.Users.FirstOrDefaultAsync(u => u.Email.Equals(userDto.Email));
It would be nice to check also uid as well as email

2022-08-30 08:48 UTC, Erbidium requested changes

2022-08-30 08:48 UTC, Erbidium commented on frontend/src/app/modules/auth/components/sign-in-form/sign-in-form.component.ts
> +                })
You should put repeating code to separate helpers. This code is same as code in sign up component

2022-08-30 08:50 UTC, Erbidium requested changes

2022-08-30 08:50 UTC, Erbidium commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/UserService.cs
> +            if (userDto is null)
If parameter is not nullable, then exception will be probably thrown automatically?

2022-08-30 09:01 UTC, Erbidium approved these changes

2022-08-30 09:04 UTC, merged