[#190] created email notification templates
BinaryStudioAcademy/bsa-2022-easymeets pull request #203
Opened 2022-08-30 14:32 UTC by Pavliuk13

![1](https://user-images.githubusercontent.com/59260347/187463957-dab8b0b0-23c4-4777-a2e1-9fb2132b386a.png)
![2](https://user-images.githubusercontent.com/59260347/187463962-9ef33dca-bc15-4c29-984b-7989b7736809.png)
![3](https://user-images.githubusercontent.com/59260347/187463967-1d19a102-ad7c-43c8-b5b6-48dc4cefe72e.png)
![4](https://user-images.githubusercontent.com/59260347/187463969-d2f6903e-cdc4-4168-ac6c-b7a71279c2a7.png)

2022-08-30 15:00 UTC, YuraRiabov requested changes

2022-08-30 15:00 UTC, YuraRiabov commented on frontend/src/app/core/helpers/notification-templates.ts
> +        default:
I think it would be better to include all enum cases in the switch

2022-08-30 15:28 UTC, Pavliuk13 commented on frontend/src/app/core/helpers/notification-templates.ts
> +        default:
Follow Up case added

2022-08-30 15:29 UTC, YuraRiabov approved these changes

2022-08-30 15:33 UTC, tatianahutii approved these changes

2022-08-31 15:30 UTC, apofis96 approved these changes

2022-08-31 15:34 UTC, merged