fixed input float labels
BinaryStudioAcademy/bsa-2022-easymeets pull request #205
Opened 2022-08-30 16:12 UTC by Pavliuk13

Before:
![23](https://user-images.githubusercontent.com/59260347/187487193-74b41cf1-faff-4e67-8e21-b95d4ad3de49.png)
After:
![22](https://user-images.githubusercontent.com/59260347/187487190-45a9b6c6-3e90-4334-b382-271a8091d9b2.png)

2022-08-30 16:21 UTC, EvgenValko approved these changes

2022-08-31 15:33 UTC, apofis96 requested changes

2022-08-31 15:33 UTC, apofis96 commented on frontend/src/app/modules/new-meeting/new-meeting/new-meeting.component.html
> +                            <i
fix style x4

2022-08-31 15:33 UTC, apofis96 commented on frontend/src/app/modules/new-meeting/new-meeting/new-meeting.component.html
> -                            <small *ngIf="customTimeShown && customTimeControl.errors?.['required']">This field is required.</small>
fix style x3

2022-08-31 15:33 UTC, apofis96 commented on frontend/src/app/modules/new-meeting/new-meeting/new-meeting.component.html
> +                            >Length must be less than 50 characters.</small
fix style x2

2022-08-31 15:33 UTC, apofis96 commented on frontend/src/app/modules/new-meeting/new-meeting/new-meeting.component.html
> +                        >
fix style

2022-08-31 16:25 UTC, Pavliuk13 commented on frontend/src/app/modules/new-meeting/new-meeting/new-meeting.component.html
> +                            <i
All fixed

2022-09-02 09:17 UTC, apofis96 approved these changes

2022-09-02 09:21 UTC, tatianahutii approved these changes

2022-09-02 09:25 UTC, merged