#191 Fix location in slot
BinaryStudioAcademy/bsa-2022-easymeets pull request #207
Opened 2022-08-30 18:27 UTC by EvgenValko

2022-08-30 18:30 UTC, koval0v approved these changes

2022-08-31 05:53 UTC, tatianahutii requested changes

2022-08-31 05:53 UTC, tatianahutii commented on frontend/src/app/modules/availability/slot/slot.component.html
> +            <p *ngIf="hasOwner">{{ slot.size }} min, {{ slot.authorName }}, {{ locationTypeValues[+slot.locationType] }}</p>
This logic looks strange

2022-08-31 14:17 UTC, tatianahutii requested changes

2022-08-31 14:17 UTC, tatianahutii commented on frontend/src/app/core/helpers/country-label-mapping.ts
> +        case 'UnitedStates':
Why there two cases?

2022-08-31 14:17 UTC, tatianahutii commented on frontend/src/app/core/helpers/location-type-mapping.ts
> +        case 'GoogleMeet':
see the previous comment

2022-08-31 14:37 UTC, EvgenValko commented on frontend/src/app/core/helpers/country-label-mapping.ts
> +        case 'UnitedStates':
Fixed

2022-08-31 14:37 UTC, EvgenValko commented on frontend/src/app/core/helpers/location-type-mapping.ts
> +        case 'GoogleMeet':
Fixed

2022-08-31 14:53 UTC, tatianahutii approved these changes
LGTM

2022-08-31 14:57 UTC, apofis96 requested changes

2022-08-31 14:57 UTC, apofis96 commented on backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
> +                });
Combine to one call

2022-08-31 15:01 UTC, apofis96 approved these changes

2022-08-31 15:04 UTC, merged