Bug/location in external booking slots #192
BinaryStudioAcademy/bsa-2022-easymeets pull request #208
Opened 2022-08-30 18:32 UTC by koval0v

![image](https://user-images.githubusercontent.com/71783287/187515693-5c15b89d-70c8-458f-9ce3-01c7224eb655.png)

2022-08-30 18:37 UTC, EvgenValko approved these changes

2022-08-31 05:38 UTC, tatianahutii requested changes

2022-08-31 05:38 UTC, tatianahutii commented on frontend/src/app/shared/enums/locationType.ts
> +    GoogleMeet = 'Google Meet',
Are you sure this will work with the backend?

2022-08-31 05:38 UTC, tatianahutii commented on frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.html
> +                        <h3>{{ LocationType[+menu.location] }}</h3>
Strange logic

2022-08-31 14:59 UTC, closed without merging