Bug/multiple team members requirements #134
BinaryStudioAcademy/bsa-2022-easymeets pull request #222
Opened 2022-09-01 12:44 UTC by koval0v

![image](https://user-images.githubusercontent.com/71783287/187916604-4c0f3d41-59e9-47db-b05b-b7cd74b614c5.png)
![image](https://user-images.githubusercontent.com/71783287/187916635-b6b7497a-beaf-4099-b0f8-f75721a69373.png)

2022-09-01 12:48 UTC, YuraRiabov approved these changes
Looks fine

2022-09-01 12:59 UTC, tatianahutii requested changes

2022-09-01 12:59 UTC, tatianahutii commented on frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.ts
> +        return this.router.url.includes('/team/') || this.menu.team != null;
```suggestion
        return this.router.url.includes('/team/') || this.menu.team;
```

2022-09-01 14:53 UTC, tatianahutii approved these changes

2022-09-02 09:15 UTC, apofis96 approved these changes

2022-09-02 09:29 UTC, merged