An unauthorized user is redirecting to the "Sign in" page #208
BinaryStudioAcademy/bsa-2022-easymeets pull request #231
Opened 2022-09-02 17:34 UTC by koval0v

Authorized:
https://bsa-easymeets.westeurope.cloudapp.azure.com ---> https://bsaeasymeets.westeurope.cloudapp.azure.com/availability
Unauthorized:
https://bsa-easymeets.westeurope.cloudapp.azure.com ---> https://bsaeasymeets.westeurope.cloudapp.azure.com/auth/signin

2022-09-02 17:36 UTC, hekeemje approved these changes
looks good

2022-09-03 06:53 UTC, tatianahutii requested changes

2022-09-03 06:53 UTC, tatianahutii commented on frontend/src/app/app-routing.module.ts
> +        path: 'landing-page',
why do we need this?

2022-09-04 12:48 UTC, tatianahutii approved these changes

2022-09-04 13:48 UTC, apofis96 approved these changes

2022-09-04 14:57 UTC, merged