Feature/alert message availability
BinaryStudioAcademy/bsa-2022-easymeets pull request #232
Opened 2022-09-03 11:28 UTC by SlakvichAleksandr

2022-09-03 12:23 UTC, Erbidium approved these changes

2022-09-04 07:51 UTC, SlakvichAleksandr commented
https://prnt.sc/GSc5li_fiWY1 - example

2022-09-04 08:55 UTC, tatianahutii requested changes

2022-09-04 08:55 UTC, tatianahutii commented on frontend/src/app/modules/header/header-item/header-item.component.ts
> +            this.teamService.getCurrentUserTeams().subscribe((teams) => {
need to unsubscibe

2022-09-04 08:55 UTC, tatianahutii commented on frontend/src/app/modules/header/header-item/header-item.component.ts
> +                }
move to a separate method

2022-09-04 08:55 UTC, tatianahutii commented on frontend/src/app/shared/components/unsaved-changes/unsaved-changes.component.ts
> +        this.message = data.message;
why do we need separate properties?

2022-09-04 10:45 UTC, tatianahutii approved these changes

2022-09-04 18:16 UTC, apofis96 approved these changes

2022-09-04 19:43 UTC, merged