#220 Zoom link generation functionality attached to meeting creation
BinaryStudioAcademy/bsa-2022-easymeets pull request #239
Opened 2022-09-04 20:15 UTC by YuraRiabov

2022-09-04 20:19 UTC, koval0v approved these changes

2022-09-04 20:23 UTC, tatianahutii requested changes

2022-09-04 20:23 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/ZoomService.cs
> +            .First(m => m.Id == meetingId);
FirstOrDefauls and check for null

2022-09-04 20:23 UTC, tatianahutii commented on frontend/src/app/modules/bookings/bookings-page/bookings-page.component.html
> +                        <button class="buttonZoom" (click)="followMeetingLink(i)">Open {{ item.location }} Link</button>
I believe we can simplify this logic

2022-09-04 20:23 UTC, tatianahutii commented
Add screenshots

2022-09-04 20:25 UTC, tatianahutii requested changes

2022-09-04 20:25 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/MeetingService.cs
> +            }
it would be better to create a separate method with switch/case for this

2022-09-05 04:49 UTC, tatianahutii approved these changes

2022-09-05 09:27 UTC, tatianahutii approved these changes

2022-09-05 09:35 UTC, apofis96 approved these changes

2022-09-05 09:38 UTC, merged