Added reusable side menu
BinaryStudioAcademy/bsa-2022-easymeets pull request #24
Opened 2022-08-10 16:28 UTC by Ymkavi

![Screenshot 2022-08-10 190313](https://user-images.githubusercontent.com/58224993/183963362-0b35f6c9-26f8-4499-8a41-3dcde929c4e2.png)
![Screenshot 2022-08-10 190454](https://user-images.githubusercontent.com/58224993/183963369-554b3092-afd9-47ec-96e2-093b153b6c64.png)

2022-08-10 18:33 UTC, tatianahutii requested changes

2022-08-10 18:33 UTC, tatianahutii commented on frontend/src/app/shared/components/side-menu/side-menu-header/side-menu-header.component.ts
> +            // eslint-disable-next-line no-use-before-define
Do not use eslint-disable

2022-08-10 18:33 UTC, tatianahutii commented on frontend/src/app/shared/components/side-menu/side-menu-item/side-menu-item.component.sass
> +    background-color: #E3ECFF
Use our color variables

2022-08-10 18:33 UTC, tatianahutii commented on frontend/src/app/shared/components/side-menu/side-menu-item/side-menu-item.component.ts
> +    // eslint-disable-next-line no-use-before-define
Do not use eslint-disable

2022-08-10 18:35 UTC, tatianahutii requested changes
Need more discussion about logic on a call

2022-08-11 10:44 UTC, tatianahutii requested changes

2022-08-11 10:44 UTC, tatianahutii commented on frontend/src/app/modules/side-menu/component/side-menu.component.html
> +        >
```suggestion
            routerLinkActive="side-list-item-active">
```

2022-08-11 10:44 UTC, tatianahutii commented on frontend/src/app/modules/side-menu/component/side-menu.component.sass
> +
Remove empty line

2022-08-11 12:39 UTC, Ymkavi commented
![Screenshot 2022-08-11 152438](https://user-images.githubusercontent.com/58224993/184135108-49d5bd41-c4a6-44f9-bacb-d86d967b9550.png)

2022-08-11 14:30 UTC, tatianahutii requested changes

2022-08-11 14:30 UTC, tatianahutii commented on frontend/src/app/modules/side-menu/component/side-menu.component.sass
> +    width: 259px
This is not a good idea to use constant px

2022-08-11 15:11 UTC, tatianahutii approved these changes
LGTM

2022-08-11 15:17 UTC, merged