#239 Ability to save slot with invalid link fixed
BinaryStudioAcademy/bsa-2022-easymeets pull request #287
Opened 2022-09-07 18:59 UTC by YuraRiabov

![Screenshot_759](https://user-images.githubusercontent.com/88149444/188956466-334989a9-31d4-4cd7-be19-070e2d687c34.png)

2022-09-07 19:44 UTC, tatianahutii requested changes

2022-09-07 19:44 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/new-availability/new-availability.component.ts
> +            this.hasAnyErrors = this.generalErrors || this.eventDetailsErrors;
Could we move this check to a separate method and reuse it?

2022-09-07 20:21 UTC, tatianahutii approved these changes

2022-09-08 07:47 UTC, Ymkavi approved these changes

2022-09-08 07:55 UTC, apofis96 approved these changes

2022-09-08 07:57 UTC, merged