#258 add duration types to general component
BinaryStudioAcademy/bsa-2022-easymeets pull request #289
Opened 2022-09-07 20:53 UTC by SlakvichAleksandr

2022-09-08 06:48 UTC, SlakvichAleksandr commented
https://prnt.sc/Qm9dTkStynLL
https://prnt.sc/eQMKZn9llckb
https://prnt.sc/ibdC-NALM7Qh

2022-09-08 08:10 UTC, SlakvichAleksandr commented
https://user-images.githubusercontent.com/78310758/189070342-a05b751f-1d82-48f6-a038-8e903652a2c2.mp4

2022-09-08 08:21 UTC, Ymkavi approved these changes

2022-09-08 10:45 UTC, tatianahutii requested changes

2022-09-08 10:45 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +        this.settings.size = this.duration.minutes!;
please get rid of mutation

2022-09-08 10:45 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +        const unitOfTime: UnitOfTime = UnitOfTime[this.selectedUnit as keyof typeof UnitOfTime];
why cannot use just this.selectedUnit

2022-09-08 10:45 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +                : parseInt(this.inputCustomTime, 10);
please a separate method to update settings size

2022-09-08 10:45 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +        this.duration = this.durations.find((x) => x.minutes === slotDuration) ?? this.durations[4];
get rid of magic number

2022-09-08 10:45 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +            this.selectedUnit = this.unitOfTime.find((x) => x === 'Min')!;
use enam

2022-09-08 14:33 UTC, tatianahutii requested changes

2022-09-08 14:33 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +        this.defineCurrentDuration(this.settings.size);
Please ger rid of push

2022-09-08 14:33 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +        this.settings.size = slotSize;
Get rid of mutation

2022-09-08 14:33 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +            this.selectedUnit = this.unitOfTime.find((x) => x === String(UnitOfTime.Min))!;
Do not use '!'

2022-09-08 14:33 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +            this.selectedUnit = this.unitOfTime.find((x) => x === String(UnitOfTime.Min))!;
Use another way. Without String

2022-09-08 17:29 UTC, tatianahutii requested changes

2022-09-08 17:29 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.sass
> +        max-width: calc(280px - 20px)
please use % or em

2022-09-08 17:29 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +            UnitOfTime[this.selectedUnit as keyof typeof UnitOfTime] === UnitOfTime.Hour
why you cannot just use this.selectedUnit as UnitOfTime?

2022-09-08 17:29 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +        };
```suggestion
        const settings: ISaveGeneralSettings = {
            ...this.settings,
            size: slotSize
        };
```

2022-09-08 17:37 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.sass
> +        max-width: calc(280px - 20px)
and I believe we don't need calc here =)

2022-09-08 18:57 UTC, tatianahutii approved these changes

2022-09-09 08:34 UTC, apofis96 approved these changes

2022-09-09 09:55 UTC, merged