Bug/availability slots shadow #249
BinaryStudioAcademy/bsa-2022-easymeets pull request #299
Opened 2022-09-08 15:31 UTC by koval0v

![image](https://user-images.githubusercontent.com/71783287/189162692-524b73db-18b5-4b0b-bd50-23c35aa7d939.png)
![image](https://user-images.githubusercontent.com/71783287/189162727-9d2e9362-6eb3-428d-8448-e4af25b8bc72.png)
![image](https://user-images.githubusercontent.com/71783287/189162751-a196cbfd-a083-41bf-99f3-682e2d453766.png)

2022-09-08 15:47 UTC, hekeemje approved these changes
looks good

2022-09-08 17:34 UTC, tatianahutii requested changes

2022-09-08 17:34 UTC, tatianahutii commented on frontend/src/app/modules/availability/slot/slot.component.ts
> +        this.slotShadowColor = ColorShadowMapping(this.slot.color).shadowHex;
It would be better to use helper 1 time and after that use return values

2022-09-09 08:07 UTC, apofis96 approved these changes

2022-09-09 08:33 UTC, merged