Auth service for client created
BinaryStudioAcademy/bsa-2022-easymeets pull request #3
Opened 2022-08-07 14:13 UTC by YuraRiabov

Sign up, sign in with email/password, sign in with google, sign out, checking if user is logged in and password reset implemented using firebase

2022-08-07 19:21 UTC, tatianahutii requested changes

2022-08-07 19:21 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +        if (currentUser === null) {
```suggestion
        if (!currentUser) {
```

2022-08-08 04:59 UTC, tatianahutii requested changes

2022-08-08 04:59 UTC, tatianahutii commented on frontend/src/app/core/services/auth.service.ts
> +import { Injectable } from '@angular/core';
Could you please add error handling for to each method (that needs it)?

2022-08-08 07:19 UTC, tatianahutii approved these changes

2022-08-08 07:28 UTC, tatianahutii commented
LGTM

2022-08-08 07:28 UTC, merged

2022-08-08 07:28 UTC, apofis96 commented on frontend/.editorconfig
> +indent_size = 4
Leave it 2. It's frontend standard (de facto)

2022-08-08 07:28 UTC, apofis96 commented on frontend/src/environments/environment.prod.ts
> +    firebase: {
It's a bad idea to commit security data to repo. Leave it with empty values.

2022-08-08 07:28 UTC, apofis96 commented on frontend/src/environments/environment.ts
> +    firebase: {
Same