Create confirm window
BinaryStudioAcademy/bsa-2022-easymeets pull request #30
Opened 2022-08-11 15:25 UTC by EvgenValko

2022-08-11 15:58 UTC, EvgenValko commented
![Screenshot_16](https://user-images.githubusercontent.com/79512847/184177236-04fccf16-fcb9-4be1-90ed-3ad57bf1ce37.png)

2022-08-12 18:10 UTC, tatianahutii requested changes

2022-08-12 18:10 UTC, tatianahutii commented on frontend/src/app/shared/components/confirmation-window/confirmation-window.component.ts
> +        if (data.acceptButton !== undefined) {
```suggestion
        if (data.acceptButton) {
```

2022-08-12 18:10 UTC, tatianahutii commented on frontend/src/app/shared/components/confirmation-window/confirmation-window.component.ts
> +        if (data.cancelButton !== undefined) {
```suggestion
        if (data.cancelButton) {
```

2022-08-12 18:10 UTC, tatianahutii commented on frontend/src/app/shared/components/confirmation-window/confirmation-window.component.html
> +</div>
It would be better to have the ability to have as many buttons as the user wants

2022-08-12 18:10 UTC, tatianahutii commented on frontend/src/app/shared/components/confirmation-window/confirmation-window.component.ts
> +    public isHasCancelButton: boolean;
I believe we can get rid of these flags

2022-08-15 07:49 UTC, tatianahutii approved these changes
LGTM

2022-08-15 07:49 UTC, merged