[#284] fixed bugs for external attendee booking functionality
BinaryStudioAcademy/bsa-2022-easymeets pull request #300
Opened 2022-09-08 16:23 UTC by Pavliuk13

- created ability to book meetings by unauthorized users
- created ability to copy link by clicking on specific icon
- fixed ability redirect to choose meeting time page by slot link

https://user-images.githubusercontent.com/59260347/189173936-2bd437ba-018b-4852-969a-47e90a4d678b.mp4

2022-09-08 16:34 UTC, koval0v approved these changes

2022-09-08 17:09 UTC, tatianahutii requested changes

2022-09-08 17:09 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/ExternalAttendeeService.cs
> +        var user = await _context.Users.Include(u => u.CreatedSlots).FirstOrDefaultAsync(u => u.PersonalUrl == personalUrl)
You can filter here

2022-09-08 17:09 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/ExternalAttendeeService.cs
> +        var slot = await _context.AvailabilitySlots.Include(s => s.Author)
it would be better to load only author

2022-09-08 17:09 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/AvailabilityController.cs
> +        [Authorize]
Please return attribute
And if you need to allow not registered user call endpoint you need to use allowanonymous attribute

2022-09-08 17:09 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Controllers/ExternalAttendeeController.cs
> +    }
you need to move this to the meeting controller

2022-09-08 17:09 UTC, tatianahutii commented on frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.ts
> +            this.getUser();
Create separate methods for cases

2022-09-08 17:09 UTC, tatianahutii commented on frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.ts
> +                    };
Please create method for updating user

2022-09-08 17:55 UTC, Pavliuk13 commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/ExternalAttendeeService.cs
> +        var slot = await _context.AvailabilitySlots.Include(s => s.Author)
I need to check availability slot link to find the one we need and check  if it's not null. So for that I have to load all slot and only after that I get author and send it to frontend.

2022-09-08 19:01 UTC, tatianahutii approved these changes

2022-09-09 08:11 UTC, apofis96 approved these changes

2022-09-09 08:15 UTC, merged