Move WebHook to Watcher and connect RabbitMQ [#256]
BinaryStudioAcademy/bsa-2022-easymeets pull request #304
Opened 2022-09-09 12:48 UTC by hekeemje

2022-09-09 13:30 UTC, Ymkavi requested changes

2022-09-09 13:30 UTC, Ymkavi commented on backend/EasyMeets.Core/EasyMeets.Core.WebAPI/Extentions/ServiceCollectionExtensions.cs
> +                var jsonSerializerSettings = new JsonSerializerSettings
Please remove this indent

2022-09-09 13:30 UTC, Ymkavi commented on backend/EasyMeets.Watcher/EasyMeets.Watcher.WebAPI/Extensions/ServiceCollectionExtensions.cs
> +﻿using EasyMeets.RabbitMQ.Interface;
Please remove this not required using

2022-09-09 13:30 UTC, Ymkavi commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/Queue/WebHookListenerService.cs
> +                throw new Exception(ex.Message);
Catching exceptions this way seems useless. We have the GenericExceptionHandler middleware

2022-09-09 13:51 UTC, Ymkavi approved these changes

2022-09-12 07:27 UTC, tatianahutii requested changes

2022-09-12 07:27 UTC, tatianahutii commented on backend/EasyMeets.RabbitMQ/Service/ConsumerService.cs
> +        public void ListenAsync(AsyncEventHandler<BasicDeliverEventArgs> messageReceivedHandler)
Why do we need an async and not an async version?

2022-09-12 07:27 UTC, tatianahutii commented on backend/EasyMeets.Watcher/EasyMeets.Watcher.BLL/EasyMeets.Watcher.BLL.csproj
> +      <ProjectReference Include="..\..\EasyMeets.RabbitMQ\EasyMeets.RabbitMQ.csproj" />
You need to add this to the dockerfile

2022-09-12 07:27 UTC, tatianahutii commented on backend/EasyMeets.Watcher/EasyMeets.Watcher.WebAPI/Controllers/WebHookController.cs
> +            return Ok();
This isn't CQRS architecture

2022-09-12 07:27 UTC, tatianahutii commented on backend/EasyMeets.Watcher/EasyMeets.Watcher.WebAPI/EasyMeets.Watcher.WebAPI.csproj
> +        <ProjectReference Include="..\EasyMeets.Watcher.BLL\EasyMeets.Watcher.BLL.csproj" />
You need to add these to the Dockerfile

2022-09-12 11:02 UTC, tatianahutii approved these changes

2022-09-12 11:12 UTC, apofis96 approved these changes

2022-09-12 11:12 UTC, merged