#280 Add the regex that accepts any Unicode languages, numbers and symbols
BinaryStudioAcademy/bsa-2022-easymeets pull request #315
Opened 2022-09-11 14:32 UTC by Ymkavi

![ukrainian](https://user-images.githubusercontent.com/58224993/189533084-825687ea-0fd2-452d-924c-e0c2fffecfe1.png)
![greek](https://user-images.githubusercontent.com/58224993/189533089-6fe753b2-6e3c-4b15-bba9-7cf381cbfb7b.png)
![mandarin](https://user-images.githubusercontent.com/58224993/189533099-16fdab71-876a-430d-90dc-d858a19a8e67.png)
![invalid](https://user-images.githubusercontent.com/58224993/189533106-c8628538-d78a-4540-b972-e77c4c535cbc.png)

2022-09-11 19:19 UTC, PublicFedorenko requested changes
Please, make sure to add automatic space removal for all inputs, **mentioned in the task**.

### For example:
![image](https://user-images.githubusercontent.com/34366638/189545116-06478423-5eb0-4b00-92f4-8a8ee0e890e2.png)
***
![image](https://user-images.githubusercontent.com/34366638/189545063-44984fe0-92bf-4fd7-bc3b-e15413bb6b2c.png)

2022-09-11 19:19 UTC, PublicFedorenko commented on frontend/src/app/shared/constants/model-validation.ts
> +);
Do we need `m` flag for multi line mode somewhere? It will allow users to input incorrect values.

E.g. first line all good and it passes validation checks as expected. The second one (after "new-line" character) is invalid but error message won't appear

![image](https://user-images.githubusercontent.com/34366638/189541478-9b0cebcb-2667-4c31-a96a-350d5404d34d.png)

```
环境指的是空气 - valid
环境指的是空气 » - invalid, but no error
```

2022-09-11 19:19 UTC, PublicFedorenko commented on frontend/src/app/modules/availability/new-slot/event-detail/event-detail.component.ts
> +
1. As of my viewpoint `message: string | null` is a bit odd. I would suggest to use [#templateVariable](https://angular.io/guide/template-reference-variables) in the component template and pass the value the same way `onWelcomeMessageChange(templateVariableName.value)`. This will pass `string` instead of `string | null`

2. The spaces should, also, be removed visually for the user

![image](https://user-images.githubusercontent.com/34366638/189541714-2be00521-dac9-41b3-bc58-29be69c5ba8f.png)

2022-09-11 19:19 UTC, PublicFedorenko commented on frontend/src/app/modules/new-meeting/new-meeting/new-meeting.component.html
> +                        >
```suggestion
                        <small *ngIf="meetingNameControl.errors?.['minlength']">Length must be more than 2 characters.</small>
                        <small *ngIf="meetingNameControl.errors?.['maxlength']">Length must be less than 50 characters.</small>
```

2022-09-11 19:19 UTC, PublicFedorenko commented on frontend/src/app/modules/settings/user/user-profile-page/user-profile-page.component.ts
> +                userName: removeExcessiveSpaces(form.value.userName),
Why do we need supplementary space removal here? Does it fix something?

2022-09-11 19:19 UTC, PublicFedorenko commented on frontend/src/app/modules/availability/edit-slot/edit-availability-page/edit-availability-page.component.ts
> +            }),
```suggestion
            questions: this.newAvailabilityComponent.questionsComponent.questions,
```
The _questions component_ should be responsible for correct processing of user input and presenting it in usable form.

2022-09-11 19:19 UTC, PublicFedorenko commented on frontend/src/app/modules/availability/new-slot/new-availability-page/new-availability-page.component.ts
> +            }),
```suggestion
            questions: this.newAvailabilityComponent.questionsComponent.questions,
```
The _questions component_ should be responsible for correct processing of user input and presenting it in a usable form.

2022-09-12 09:29 UTC, PublicFedorenko approved these changes

2022-09-12 09:49 UTC, apofis96 approved these changes

2022-09-12 09:53 UTC, tatianahutii approved these changes

2022-09-12 09:54 UTC, merged