SyncCalendars and One Callendar in two accounts [#342] [#334]
BinaryStudioAcademy/bsa-2022-easymeets pull request #354
Opened 2022-09-13 16:36 UTC by hekeemje

https://user-images.githubusercontent.com/79774156/189955474-f5b6f9da-e148-4714-9261-5858ae1d7379.mp4

as you can see here if I do changes in my Google Calendar  - this event show in schedule when we create Meeting

https://user-images.githubusercontent.com/79774156/189957637-1e906d93-ec0b-45cb-9269-298789b7fcb2.mp4

here as you can see I add one Google callendar in two accounts

2022-09-13 17:40 UTC, Ymkavi requested changes

2022-09-13 17:40 UTC, Ymkavi commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/CalendarsService.cs
> +            if (calendars is null)
ToListAsync on an empty sequence will return an empty list, not null

2022-09-13 17:41 UTC, Ymkavi requested changes
My friday event is not synced:
![image](https://user-images.githubusercontent.com/58224993/189972827-01e26422-4ef6-4bdc-9bae-8a064f6318e5.png)
![image](https://user-images.githubusercontent.com/58224993/189972839-ca5cd500-b89f-43b4-940c-dd01785c547f.png)

2022-09-13 18:04 UTC, hekeemje commented
> My friday event is not synced: ![image](https://user-images.githubusercontent.com/58224993/189972827-01e26422-4ef6-4bdc-9bae-8a064f6318e5.png) ![image](https://user-images.githubusercontent.com/58224993/189972839-ca5cd500-b89f-43b4-940c-dd01785c547f.png)

on this issue already Yura works

2022-09-13 18:05 UTC, Ymkavi approved these changes

2022-09-13 18:10 UTC, tatianahutii requested changes

2022-09-13 18:10 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/CalendarsService.cs
> +            if (await _context.Calendars.Where(el => el.ConnectedCalendar == connectedEmail).AnyAsync(el => el.UserId == currentUser.Id))
You can combine where and any

2022-09-13 18:37 UTC, tatianahutii approved these changes

2022-09-14 09:23 UTC, apofis96 approved these changes

2022-09-14 10:04 UTC, merged