#324 Redesign the schedule week view
BinaryStudioAcademy/bsa-2022-easymeets pull request #366
Opened 2022-09-14 13:25 UTC by Ymkavi

![image](https://user-images.githubusercontent.com/58224993/190165091-adf5fac3-1eb2-40cc-99f6-cf92443d2412.png)

2022-09-14 13:59 UTC, Erbidium requested changes

2022-09-14 13:59 UTC, Erbidium commented on frontend/src/app/modules/availability/new-slot/schedule-week/schedule-week.component.sass
> +        width: calc(100% - 60px)
Maybe we can change layout in order not to do such calculations?

2022-09-14 13:59 UTC, Erbidium commented on frontend/src/app/modules/availability/new-slot/schedule-week/schedule-week.component.sass
> +        width: calc(100% - 50px)
Same

2022-09-14 13:59 UTC, Erbidium commented on frontend/src/app/modules/availability/new-slot/schedule-week/schedule-week.component.sass
> +            width: calc(100% - 40px)
Same

2022-09-14 13:59 UTC, Erbidium commented on frontend/src/app/modules/availability/new-slot/schedule-week/schedule-week.component.sass
> +            width: calc(100% - 28px)
Same

2022-09-14 17:25 UTC, tatianahutii approved these changes

2022-09-14 17:54 UTC, Erbidium approved these changes

2022-09-15 16:29 UTC, apofis96 approved these changes

2022-09-15 16:40 UTC, merged