#354 Displaying unavailable time of team members fixed
BinaryStudioAcademy/bsa-2022-easymeets pull request #368
Opened 2022-09-14 14:47 UTC by YuraRiabov

![Screenshot_847](https://user-images.githubusercontent.com/88149444/190187157-684e7f15-82a8-4ab9-8ddc-0a83388feef4.png)
![Screenshot_848](https://user-images.githubusercontent.com/88149444/190187189-d4e93d46-61f8-4650-9777-36315787c05f.png)

2022-09-14 14:53 UTC, olena-kozak approved these changes

2022-09-14 17:29 UTC, tatianahutii requested changes

2022-09-14 17:29 UTC, tatianahutii commented on frontend/src/app/modules/new-meeting/new-meeting-calendar/new-meeting-calendar.component.ts
> +        if (unstrict === true) {
```suggestion
        if (unstrict) {
```

2022-09-14 17:29 UTC, tatianahutii commented on frontend/src/app/modules/new-meeting/new-meeting-calendar/new-meeting-calendar.component.ts
> +    private containsDate(date: Date, start: Date, end: Date, unstrict?: boolean) {
Move to the date helper

2022-09-14 17:29 UTC, tatianahutii commented on frontend/src/app/modules/new-meeting/new-meeting-calendar/new-meeting-calendar.component.ts
> +                this.containsDate(unavailability.end, date, dateEnd, true));
Add two different methods and use them

2022-09-14 17:29 UTC, tatianahutii commented on frontend/src/app/modules/new-meeting/new-meeting-calendar/new-meeting-calendar.component.ts
> +                merged.push(mergedEvent);
Why push?

2022-09-14 17:29 UTC, tatianahutii commented on frontend/src/app/modules/new-meeting/new-meeting-calendar/new-meeting-calendar.component.ts
> +                end: currentIntercepting.reduce((p, c) => (p.end > c.end ? p : c)).end,
create a separate method for reduce

2022-09-14 17:29 UTC, tatianahutii commented on frontend/src/app/modules/new-meeting/new-meeting-calendar/new-meeting-calendar.component.ts
> +        events.map((value, index, array) => {
Wrong using of map

2022-09-15 07:51 UTC, tatianahutii approved these changes

2022-09-15 16:37 UTC, apofis96 approved these changes

2022-09-15 16:41 UTC, merged