#265 Booking redesign
BinaryStudioAcademy/bsa-2022-easymeets pull request #374
Opened 2022-09-15 16:20 UTC by YuraRiabov

![Screenshot_868](https://user-images.githubusercontent.com/88149444/190455931-4f5d22f5-89e5-464e-aeb9-06d120750f90.png)
![Screenshot_869](https://user-images.githubusercontent.com/88149444/190455951-98139427-6f54-4578-bab9-1736bb721f5c.png)

2022-09-15 16:42 UTC, EvgenValko approved these changes

2022-09-15 16:52 UTC, tatianahutii requested changes

2022-09-15 16:52 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Interfaces/IMeetingService.cs
> +        Task<List<MeetingSlotDTO>> GetMeetingMembersByNumberOfMembersToDisplayAsync(MeetingMemberRequestDto meetingMemberRequestDto);
Tooooo long name

2022-09-15 16:52 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/MeetingService.cs
> +                .OrderBy(m => m.StartTime)
Please connect two where

2022-09-15 16:52 UTC, tatianahutii commented on frontend/src/app/modules/bookings/booker/booker.component.sass
> +.itemText
please use common style name style

2022-09-15 16:52 UTC, tatianahutii commented on frontend/src/app/modules/bookings/bookings-page/bookings-page.component.html
> +                <p *ngIf="selectedDateFilter === 'Pending'" class="date-label">Future Meetings</p>
```suggestion
                <p *ngIf="selectedDateFilter === 'Pending'" class="date-label">Pending Meetings</p>
```

2022-09-15 16:52 UTC, tatianahutii commented on frontend/src/app/modules/bookings/bookings-page/bookings-page.component.html
> +                            <span *ngIf="selectedDateFilter !== 'Today'" class="timeTitle">{{ item.meetingTime | date:'d LLLL'}}, {{ item.meetingTime | date: 'HH:mm':getTimeZoneValue() }}</span>
Cannot we combine these items?

2022-09-15 16:52 UTC, tatianahutii commented on frontend/src/app/modules/bookings/bookings-page/bookings-page.component.html
> +                                    <p>+{{ item.meetingMembers.length - 10 }}</p>
please get rid of magic number

2022-09-15 16:52 UTC, tatianahutii commented on frontend/src/app/modules/bookings/bookings-page/bookings-page.component.ts
> +    }
Please refactor this method

2022-09-15 16:52 UTC, tatianahutii commented on frontend/src/app/modules/bookings/bookings-page/bookings-page.component.ts
> +        }
It would be better to know the size of one item and dynamic calculate items' count

2022-09-15 19:41 UTC, tatianahutii approved these changes

2022-09-16 09:07 UTC, apofis96 approved these changes

2022-09-16 09:09 UTC, merged