#266 Redesign the Setting Page
BinaryStudioAcademy/bsa-2022-easymeets pull request #383
Opened 2022-09-16 15:16 UTC by PublicFedorenko

Closes [266-redesign-the-setting-page](https://trello.com/c/kKSfaiTN/266-redesign-the-setting-page)

https://user-images.githubusercontent.com/34366638/190659516-f05e2105-098e-424c-8623-4e9485d835e5.mp4

https://user-images.githubusercontent.com/34366638/190660012-a0c99cf7-c2ef-4d5a-bf87-8a5c8d884f32.mp4

2022-09-16 16:39 UTC, tatianahutii approved these changes

2022-09-18 16:09 UTC, tatianahutii requested changes

2022-09-18 16:09 UTC, tatianahutii commented on frontend/src/styles/color-variables.sass
> +$gray-7: #4A505C
Please get rid of numbers

2022-09-21 11:29 UTC, PublicFedorenko commented on frontend/src/styles/color-variables.sass
> +$gray-7: #4A505C
Done

2022-09-21 11:39 UTC, Pavliuk13 approved these changes

2022-09-21 11:55 UTC, tatianahutii approved these changes

2022-09-21 12:49 UTC, apofis96 approved these changes

2022-09-21 12:54 UTC, merged