Send Remind/FollowUp emails in choosen time [#299]
BinaryStudioAcademy/bsa-2022-easymeets pull request #384
Opened 2022-09-16 20:06 UTC by hekeemje

2022-09-17 07:58 UTC, koval0v approved these changes

2022-09-17 13:38 UTC, hekeemje commented
![image](https://user-images.githubusercontent.com/79774156/190859867-cb757066-75a0-4031-b814-7866417e582d.png)

2022-09-18 16:12 UTC, tatianahutii requested changes

2022-09-18 16:12 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/Quartz/EmailDelayJob.cs
> +            Task.Run(() => emailDelayService.CheckForNotify()).Wait();
Task.Run won't give you async execusion

2022-09-18 16:12 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/Quartz/EmailDelayService.cs
> +            var avslots = _context.AvailabilitySlots.ToList();
not good idea to load all slots

2022-09-18 16:12 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/Quartz/EmailDelayService.cs
> +            }
foreach in foreach is not a good idea

2022-09-18 16:12 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/Quartz/EmailDelayService.cs
> +                    }
see the previous comment

2022-09-19 11:52 UTC, tatianahutii requested changes

2022-09-19 11:52 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/Quartz/EmailDelayService.cs
> +                .Where(x => (x.TemplateType == TemplateType.Reminders && x.IsSend == true) || (x.TemplateType == TemplateType.FollowUp && x.IsSend == true))
```suggestion
                .Where(x => (x.TemplateType == TemplateType.Reminders && x.IsSend) || (x.TemplateType == TemplateType.FollowUp && x.IsSend))
```

2022-09-19 11:52 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/Quartz/EmailDelayService.cs
> +                .Select(x => x.AvailabilitySlot).ToListAsync();
```suggestion
                .Select(x => x.AvailabilitySlot)
                .ToListAsync();
```

2022-09-19 11:52 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/Quartz/EmailDelayService.cs
> +            await Task.CompletedTask;
You can use task.whenall

2022-09-19 11:52 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/Quartz/EmailDelayService.cs
> +                _ = slot.Meetings.Select(async x => await CheckAndSend(minutes, x, templateType));
It would be better to wait for all not one simple template

2022-09-19 12:44 UTC, tatianahutii approved these changes

2022-09-21 11:51 UTC, apofis96 approved these changes

2022-09-21 12:03 UTC, merged