#301 Ability to create team slots implemented
BinaryStudioAcademy/bsa-2022-easymeets pull request #385
Opened 2022-09-17 17:44 UTC by YuraRiabov

![Screenshot_888](https://user-images.githubusercontent.com/88149444/190869714-80daee52-bb4b-4073-ac11-a4224a418ecd.png)
![Screenshot_889](https://user-images.githubusercontent.com/88149444/190869717-6bca3483-55c1-4bfe-a210-06616acb3b7f.png)

2022-09-17 19:00 UTC, Erbidium commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/AvailabilityService.cs
> +                member.ScheduleId = availabilitySlot.SlotMembers.First().ScheduleId;
maybe we should add check to First() like "member => member.MemberId == availabilitySlot.CreatedBy" which can be seen below

2022-09-17 19:48 UTC, Erbidium approved these changes

2022-09-18 16:19 UTC, tatianahutii requested changes

2022-09-18 16:19 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/AvailabilityService.cs
> +
Why do we need this? Every member have their own schedule

2022-09-18 16:19 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/AvailabilityService.cs
> +            var scheduleId = availabilitySlot.SlotMembers.First(member => member.MemberId == availabilitySlot.CreatedBy)
see the previous comment

2022-09-18 16:19 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/schedule/schedule.component.ts
> +    }
Use one style format (with or without public word)

2022-09-18 16:19 UTC, tatianahutii commented on frontend/src/app/shared/components/slot-members-window/slot-members-window.component.ts
> +                    .filter(member => !this.alreadySelected.some(m => m.memberId === member.memberId));
move to a separate method

2022-09-18 16:19 UTC, tatianahutii commented on frontend/src/app/shared/components/slot-members-window/slot-members-window.component.ts
> +        this.teamService.getTeamMembers(this.teamId)
why in the constructor?

2022-09-19 10:55 UTC, tatianahutii approved these changes

2022-09-19 11:54 UTC, apofis96 requested changes

2022-09-19 11:54 UTC, apofis96 commented on frontend/src/app/modules/availability/new-slot/schedule/schedule.component.html
> +            <button mat-flat-button (click)="openAddMembers()">+ Add Team Member (s)</button>
use plus icon

2022-09-19 12:06 UTC, apofis96 approved these changes

2022-09-19 12:07 UTC, merged