[#346] advanced slot settings applying
BinaryStudioAcademy/bsa-2022-easymeets pull request #386
Opened 2022-09-17 18:11 UTC by Pavliuk13

2022-09-18 16:28 UTC, tatianahutii requested changes

2022-09-18 16:28 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +            paddingMeeting: this.slot?.advancedSlotSettings?.paddingMeeting ?? this.durations[0].minutes!,
Could you avoid !

2022-09-18 16:28 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +            startDate: this.slot?.advancedSlotSettings?.startDate ?? new Date(new Date().setHours(0, 0, 0, 0)),
Please our date library for this (startOfDay)

2022-09-18 16:28 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +            paddingMeeting: this.durations[0].minutes!,
see the previous comment

2022-09-18 16:28 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +            minBookingMeetingDifference: this.durations[0].minutes!,
see the previous comment

2022-09-18 16:28 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +        this.updateSettings(this.inputSettings[index].durationValue?.minutes!, this.inputSettings[index].inputType);
Could we get rid of the index? and why do we need it?

2022-09-18 16:28 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +            startDate: new Date(this.startDate.setHours(0, 0, 0, 0)),
see the previous comments

2022-09-18 16:28 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +    }
looks strange

2022-09-18 16:28 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/general/general.component.ts
> +                }
Please refactor

2022-09-18 16:28 UTC, tatianahutii commented on frontend/src/app/modules/external-booking/external-booking-choose-time-page/external-booking-choose-time-page.component.ts
> +                this.disabledDays = this.scheduleItems.filter((el) => !el.isEnabled).map((el) => WeekDay[el.weekDay]);
Toooo long method

2022-09-18 16:28 UTC, tatianahutii commented on frontend/src/app/modules/external-booking/external-booking-choose-time-page/external-booking-choose-time-page.component.ts
> +                this.isBookingsLimit = maxBookingsCount !== 0 && this.orderedTimes.length >= maxBookingsCount;
```suggestion
                this.isBookingsLimit = !!maxBookingsCount && this.orderedTimes.length >= maxBookingsCount;
```

2022-09-18 16:28 UTC, tatianahutii commented on frontend/src/app/modules/external-booking/external-booking-choose-time-page/external-booking-choose-time-page.component.ts
> +                }
Move to a separate method

2022-09-18 16:28 UTC, tatianahutii commented on frontend/src/app/modules/external-booking/external-booking-choose-time-page/external-booking-choose-time-page.component.ts
> +            );
please get rid of !, refactor and move to a separate method

2022-09-18 21:12 UTC, Erbidium requested changes

2022-09-18 21:12 UTC, Erbidium commented on frontend/src/app/modules/availability/new-slot/general/custom-time/custom-time.component.sass
> +        max-width: calc(280px - 9px)
I think we can simply write 271px)

2022-09-18 21:12 UTC, Erbidium commented on frontend/src/app/modules/availability/new-slot/general/custom-time/custom-time.component.sass
> +        width: calc(100% - 9px)
Why we need this?

2022-09-18 21:12 UTC, Erbidium commented on frontend/src/app/modules/availability/new-slot/general/general.component.html
> +            <!-- custom duration for duration -->
Do we need this comment?

2022-09-18 21:12 UTC, Erbidium commented on frontend/src/app/modules/availability/new-slot/general/general.component.html
> +                    (changeValueEmitter)="customDurationChanged($event)"></app-custom-time>
Closing tag should be on the next line) It doesn't look beatiful)

2022-09-18 21:12 UTC, Erbidium commented on frontend/src/app/modules/availability/new-slot/general/general.component.html
> +            <!-- custom duration for frequency -->
Same

2022-09-18 21:12 UTC, Erbidium commented on frontend/src/app/modules/availability/new-slot/general/general.component.html
> +                    (changeValueEmitter)="customFrequencyChanged($event)"></app-custom-time>
Same

2022-09-18 21:12 UTC, Erbidium commented on frontend/src/app/modules/availability/new-slot/general/general.component.html
> +            <!-- custom duration for paddings -->
Same

2022-09-18 21:12 UTC, Erbidium commented on frontend/src/app/modules/availability/new-slot/general/general.component.html
> +                    (changeValueEmitter)="customPaddingChanged($event)"></app-custom-time>
Same

2022-09-18 21:12 UTC, Erbidium commented on frontend/src/app/modules/availability/new-slot/general/general.component.sass
>      max-width: calc(280px - 9px)
Simply 271px

2022-09-19 15:53 UTC, Erbidium approved these changes

2022-09-20 16:56 UTC, apofis96 requested changes

2022-09-20 16:56 UTC, apofis96 commented on frontend/src/app/modules/availability/new-slot/general/custom-time/custom-time.component.sass
> +::ng-deep .input-container
input-container are likely to be used in other component

2022-09-21 08:29 UTC, apofis96 approved these changes

2022-09-21 08:34 UTC, tatianahutii approved these changes

2022-09-21 08:47 UTC, merged