#323 Feature/month view
BinaryStudioAcademy/bsa-2022-easymeets pull request #394
Opened 2022-09-20 06:49 UTC by EvgenValko

![Screenshot_1](https://user-images.githubusercontent.com/79512847/191187068-4a50c562-bc78-43e7-9fdd-6004a2bfc2a2.png)

2022-09-20 07:08 UTC, Pavliuk13 requested changes

2022-09-20 07:08 UTC, Pavliuk13 commented on frontend/src/app/modules/availability/new-slot/schedule-month/schedule-month.component.html
> +            <i class="fa-solid fa-repeat" *ngIf="getWeekScheduleTime(day.date).length > 0"></i>
```suggestion
            <i class="fa-solid fa-repeat" *ngIf="getWeekScheduleTime(day.date).length"></i>
```

2022-09-20 07:08 UTC, Pavliuk13 commented on frontend/src/app/modules/availability/new-slot/schedule-month/schedule-month.component.html
> +                <p *ngIf="getWeekScheduleTime(day.date).length === 0">Unavailable</p>
```suggestion
                <p *ngIf="!getWeekScheduleTime(day.date).length">Unavailable</p>
```

2022-09-20 07:34 UTC, Pavliuk13 approved these changes

2022-09-20 07:57 UTC, tatianahutii requested changes

2022-09-20 07:57 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/schedule-month/schedule-month.component.html
> +            <i class="fa-solid fa-repeat" *ngIf="getWeekScheduleTime(day.date).length > 0"></i>
```suggestion
            <i class="fa-solid fa-repeat" *ngIf="getWeekScheduleTime(day.date).length"></i>
```

2022-09-20 07:57 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/schedule-month/schedule-month.component.html
> +                <p *ngIf="getWeekScheduleTime(day.date).length === 0">Unavailable</p>
```suggestion
                <p *ngIf="!getWeekScheduleTime(day.date).length">Unavailable</p>
```

2022-09-20 07:57 UTC, tatianahutii commented on frontend/src/app/modules/availability/new-slot/schedule-month/schedule-month.component.ts
> +            .map(item => `${item.start.substring(0, 5)}-${item.end.substring(0, 5)}`);
Could you use date pipe?

2022-09-20 07:57 UTC, tatianahutii commented on frontend/src/app/shared/components/time-picker-dialog/time-picker-dialog.component.ts
> +        this.end = scheduleItem.end.substring(0, 5);
see the previous comment

2022-09-20 07:57 UTC, tatianahutii commented on frontend/src/app/shared/components/time-picker-dialog/time-picker-dialog.component.ts
> +        this.scheduleItem.end = this.end;
Please get rid of mutations

2022-09-20 07:57 UTC, tatianahutii commented on frontend/src/app/shared/components/time-picker-dialog/time-picker-dialog.component.ts
> +        return date;
why do we need this?

2022-09-20 08:04 UTC, EvgenValko commented on frontend/src/app/modules/availability/new-slot/schedule-month/schedule-month.component.html
> +            <i class="fa-solid fa-repeat" *ngIf="getWeekScheduleTime(day.date).length > 0"></i>
fix

2022-09-20 08:04 UTC, EvgenValko commented on frontend/src/app/modules/availability/new-slot/schedule-month/schedule-month.component.html
> +                <p *ngIf="getWeekScheduleTime(day.date).length === 0">Unavailable</p>
fix

2022-09-21 12:27 UTC, tatianahutii approved these changes

2022-09-21 12:43 UTC, apofis96 requested changes

2022-09-21 12:43 UTC, apofis96 commented on frontend/src/app/modules/availability/new-slot/schedule-month/schedule-month.component.sass
> +::ng-deep .mat-menu-panel
add wrapper

2022-09-21 13:17 UTC, apofis96 requested changes

2022-09-21 13:17 UTC, apofis96 commented on frontend/src/app/modules/availability/new-slot/schedule-month/schedule-month.component.sass
> +::ng-deep schedule-month-drop-down-menu
this is not class

2022-09-21 13:20 UTC, apofis96 approved these changes

2022-09-21 13:28 UTC, merged