#353 Add the ability to edit meeting
BinaryStudioAcademy/bsa-2022-easymeets pull request #395
Opened 2022-09-20 10:29 UTC by Ymkavi

https://user-images.githubusercontent.com/58224993/191234061-40e2c5ef-fb69-4dda-9520-679b91f1085d.mp4

2022-09-20 12:24 UTC, YuraRiabov approved these changes

2022-09-20 13:29 UTC, tatianahutii requested changes

2022-09-20 13:29 UTC, tatianahutii commented on frontend/src/app/app-routing.module.ts
> +    },
Why do we need a separate module for this?

2022-09-20 13:29 UTC, tatianahutii commented on frontend/src/app/modules/edit-meeting/edit-meeting/edit-meeting.component.ts
> +                });
Please get rid of subscribe in subscribe

2022-09-20 13:29 UTC, tatianahutii commented on frontend/src/app/modules/new-meeting/new-meeting/new-meeting.component.ts
> +    }
Move to a separate method

2022-09-20 13:29 UTC, tatianahutii commented on frontend/src/app/modules/new-meeting/new-meeting/new-meeting.component.ts
> +    }
Need refactoring

2022-09-21 08:06 UTC, tatianahutii approved these changes

2022-09-21 08:28 UTC, apofis96 requested changes

2022-09-21 08:28 UTC, apofis96 commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/MeetingService.cs
> +            }
combine with ??

2022-09-21 08:28 UTC, apofis96 commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/MeetingService.cs
> +            }
combine with ??

2022-09-21 09:32 UTC, apofis96 approved these changes

2022-09-21 09:40 UTC, merged