#380 Load some members to list when creating a meeting
BinaryStudioAcademy/bsa-2022-easymeets pull request #410
Opened 2022-09-21 16:29 UTC by Ymkavi

![image](https://user-images.githubusercontent.com/58224993/191559796-b5584c9f-65ae-454c-b01d-9af29ea39bb6.png)

2022-09-21 17:02 UTC, hekeemje requested changes

2022-09-21 17:02 UTC, hekeemje commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/TeamService.cs
> +        }
instead of foreach - you can use .Select and then wait for all , it will make code faster ) because your result dont depend on each other

2022-09-21 17:32 UTC, hekeemje approved these changes
looks good ( for my opinion, not expert in front side )

2022-09-22 06:53 UTC, apofis96 approved these changes

2022-09-22 07:53 UTC, tatianahutii approved these changes

2022-09-22 08:04 UTC, merged