Add location type Mapping [#389]
BinaryStudioAcademy/bsa-2022-easymeets pull request #411
Opened 2022-09-21 16:55 UTC by hekeemje

![image](https://user-images.githubusercontent.com/79774156/191565420-c71598f8-ea7a-48ab-9bc4-fb9bfade5aee.png)

2022-09-21 17:14 UTC, Ymkavi requested changes
Add mapping to another locations on the page:

![image](https://user-images.githubusercontent.com/58224993/191568838-374616b3-b6d8-455d-9efd-002f2355b4a5.png)

2022-09-21 17:31 UTC, hekeemje commented
> Add mapping to another locations on the page:
> 
> ![image](https://user-images.githubusercontent.com/58224993/191568838-374616b3-b6d8-455d-9efd-002f2355b4a5.png)

![image](https://user-images.githubusercontent.com/79774156/191572057-76dc5a12-15cb-4e3e-9449-acebcc016715.png)

2022-09-21 17:48 UTC, Ymkavi approved these changes

2022-09-22 06:51 UTC, apofis96 approved these changes

2022-09-22 08:01 UTC, tatianahutii approved these changes

2022-09-22 08:10 UTC, merged