change header style
BinaryStudioAcademy/bsa-2022-easymeets pull request #69
Opened 2022-08-17 16:38 UTC by SlakvichAleksandr

2022-08-17 16:51 UTC, SlakvichAleksandr commented
https://prnt.sc/pC1Be7JfH_ij
результат

2022-08-17 20:01 UTC, tatianahutii requested changes

2022-08-17 20:01 UTC, tatianahutii commented on frontend/src/app/modules/header/header-item/header-item.component.sass
> +.menuTeam-btn
```suggestion
.menu-team-btn
```

2022-08-18 07:51 UTC, tatianahutii approved these changes
LGTM

2022-08-18 07:51 UTC, merged