Feature/database scheme
BinaryStudioAcademy/bsa-2022-easymeets pull request #8
Opened 2022-08-08 14:41 UTC by Pavliuk13

database schema created

2022-08-08 14:48 UTC, tatianahutii requested changes
Please review the changed/added files
We don't need package-lock files and the second yarn.lock file

2022-08-08 16:32 UTC, tatianahutii requested changes

2022-08-08 16:32 UTC, tatianahutii commented on README.md
> +  Role {
Could you please remove the Role table?

2022-08-08 19:47 UTC, Erbidium commented on README.md
> +  Role {
Removed

2022-08-08 19:48 UTC, Erbidium commented
> Please review the changed/added files We don't need package-lock files and the second yarn.lock file

Removed unnecessary files)

2022-08-09 05:02 UTC, tatianahutii approved these changes

2022-08-09 05:02 UTC, merged