fixed messages in login form fields
BinaryStudioAcademy/bsa-2022-easymeets pull request #81
Opened 2022-08-18 15:15 UTC by Pavliuk13

**Try to send empty fields:**
![1](https://user-images.githubusercontent.com/59260347/185430696-29e0795c-a928-44d5-aabe-7b9f484e908f.png)
**Empty password field and email that doesn't exist in database:**
![2](https://user-images.githubusercontent.com/59260347/185430816-5fc1f3f7-e08a-47e6-8156-48942e1d820b.png)
**Correct email but password length less than 8 characters:**
![3](https://user-images.githubusercontent.com/59260347/185430848-4ae9b8ff-7c2c-42cd-9370-adee95855dca.png)
**Correct email but password is incorrect:**
![4](https://user-images.githubusercontent.com/59260347/185430853-faf17186-fd7e-44a2-8ae7-753a9096708f.png)

2022-08-18 15:19 UTC, tatianahutii requested changes

2022-08-18 15:19 UTC, tatianahutii commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/UserService.cs
> +        }
You can Use Any here

2022-08-18 15:27 UTC, Pavliuk13 commented on backend/EasyMeets.Core/EasyMeets.Core.BLL/Services/UserService.cs
> +        }
done

2022-08-19 08:55 UTC, tatianahutii approved these changes
LGTM

2022-08-19 09:01 UTC, merged