save user to local storage
BinaryStudioAcademy/bsa-2022-easymeets pull request #95
Opened 2022-08-19 07:08 UTC by SlakvichAleksandr

2022-08-19 07:52 UTC, SlakvichAleksandr commented
#85 - таска в трелло

2022-08-19 08:07 UTC, tatianahutii requested changes

2022-08-19 08:07 UTC, tatianahutii commented on frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.ts
> +        this.selectedUser = JSON.parse(user!) as IUser;
You cannot use local storage in other services

2022-08-19 08:07 UTC, tatianahutii commented on frontend/src/app/modules/user/user-profile-page/user-profile-page.component.ts
> +                    localStorage.setItem('user', JSON.stringify(user));
See the previous comment

2022-08-19 08:07 UTC, tatianahutii commented on frontend/src/app/modules/user/user-profile-page/user-profile-page.component.ts
> +        const currentUser = localStorage.getItem('user');
See the previous comment

2022-08-19 08:07 UTC, tatianahutii commented on frontend/src/app/modules/availability/availability-page/availability-page.component.ts
> +        this.currentUser = JSON.parse(user!) as IUser;
See the previous comment

2022-08-19 08:07 UTC, tatianahutii commented on frontend/src/app/modules/auth/components/sign-up-form/sign-up-form.component.ts
> +                        localStorage.setItem('user', JSON.stringify(user));
Move this to the Auth method

2022-08-19 08:07 UTC, tatianahutii commented on frontend/src/app/core/services/user.service.ts
> +        );
We need not all this data

2022-08-22 09:54 UTC, tatianahutii requested changes

2022-08-22 09:54 UTC, tatianahutii commented on frontend/src/app/modules/external-booking/external-booking-page/external-booking-page.component.ts
>      constructor(public spinnerService: SpinnerService, private userService: UserService) {
please delete eslint-disable

2022-08-22 09:54 UTC, tatianahutii commented on frontend/src/app/modules/user/user-profile-page/user-profile-page.component.ts
> +                    this.userService.setUser(user);
Please create a separate method in the service for updating

2022-08-22 11:05 UTC, tatianahutii approved these changes

2022-08-22 11:26 UTC, merged